import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture,intent,maker} from './fixtures/orderActions.ts';
import {MarketAnalysisService} from '../src/sdk/actions/marketAnalysis.ts';
import {wireOffer} from '../src/sdk/relayer.ts';
import {entryFromSignedOffer} from '../src/sdk/orderbook.ts';
function setup(){const f=fixture(),read=f.context.rpc.readContract;f.context.rpc.readContract=async r=>r.functionName==='position'?{debt:0n,collateral:0n,collateralWithdrawable:0n}:read(r);f.context.options.book=async()=>({entries:[],source:'fixture',coverage:'complete'});const policies={test:{...f.actions.policies.test,inventory:{[intent.marketId]:{maxCredit:'150',maxNewDebt:'0',minCash:'0',maxCommittedLoan:'1000',maxLoss:'1000',allowOrigination:false}}}};const service=new MarketAnalysisService(f.context,policies,f.service.journal);return{...f,orderService:f.service,policies,service,wire:(o:any)=>({...wireOffer(f.context.profile,o),chainId:f.context.profile.chainId})};}
test('MM adapter rebuilds prices, includes journal exposure and never gives account safe verdict',async()=>{const f=setup(),p=await f.orderService.prepare({...intent,maxUnits:'60'});const r=await f.service.mmPreview({account:maker.address,marketIds:[intent.marketId],candidateOffers:[],policyId:'test'});assert.equal(r.data.accountSafe,false);assert.equal(r.snapshot?.coverage,'partial');assert.equal(r.data.markets[0].analysis?.decision,'reject');assert.equal(r.data.markets[0].knownOrders,1);});
test('MM requires trusted limits and reports unavailable book/state as incomplete',async()=>{const f=setup();await assert.rejects(f.service.mmPreview({account:maker.address,marketIds:[intent.marketId],candidateOffers:[],policyId:'unknown'}),/POLICY_REJECTED/);f.context.options.book=async()=>{throw new Error('offline');};const read=f.context.rpc.readContract;f.context.rpc.readContract=async r=>{if(r.functionName==='creditOf')throw new Error('offline');return read(r);};const r=await f.service.mmPreview({account:maker.address,marketIds:[intent.marketId],candidateOffers:[],policyId:'test'});assert.equal(r.data.markets[0].analysis,null);assert.ok(r.snapshot!.omitted.some(x=>x.includes('book')));});
test('arbitrage binds signed ticks, same market and face; no atomic or lower bound claim',async()=>{const f=setup(),p=await f.orderService.prepare(intent);const other=`0x${'77'.repeat(20)}` as const;const leg=(buy:boolean,tick:bigint)=>{const offer={...p.data.offer,maker:other,buy,tick};return{offer:f.wire(offer),commitment:f.context.adapter.offerCommitment(f.context.profile,offer),ratifierData:'0x' as const,units:'5'};};const entry=leg(false,4000n),exit=leg(true,5000n);const r=await f.service.arbitragePreview({account:maker.address,entry:[entry],exit:[exit],minProfit:'0',gasBudget:'1'});assert.equal(r.data.kind,'estimated_spread');assert.equal(r.data.netProfitLowerBound,null);assert.equal(r.data.guaranteedProfit,false);await assert.rejects(f.service.arbitragePreview({account:maker.address,entry:[entry],exit:[{...exit,units:'6'}],minProfit:'0'}),/INVALID_ARGUMENT/);await assert.rejects(f.service.arbitragePreview({account:maker.address,entry:[entry],exit:[exit],minProfit:'0',atomicVerification:{simulated:true}} as any),/INVALID_ARGUMENT/);});
import {createMarketAnalysisTools} from '../src/mcp/tools/mm.ts';
test('MCP transport exposes inventory rejection and rejects caller derived prices',async()=>{const f=setup(),p=await f.orderService.prepare({...intent,maxUnits:'60'});const tool=createMarketAnalysisTools(f.context,f.policies,f.orderService.journal).find(t=>t.name==='mm_preview')!;const r=await tool.handler({account:maker.address,marketIds:[intent.marketId],candidateOffers:[],policyId:'test'},{signal:new AbortController().signal} as any) as any;assert.equal(r.data.decision,'reject');await assert.rejects(f.service.mmPreview({account:maker.address,marketIds:[intent.marketId],candidateOffers:[{...f.wire(p.data.offer),price:'1'}],policyId:'test'}),/INVALID_ARGUMENT/);});
test('MM reconstructs relayer size and price and deduplicates journal commitments',async()=>{const f=setup(),p=await f.orderService.prepare({...intent,maxUnits:'60'});f.context.options.book=async()=>({entries:[{...entryFromSignedOffer(p.data.offer,p.data.commitment,'0x'),price:0n,size:0n}],source:'fixture',coverage:'complete'});const r=await f.service.mmPreview({account:maker.address,marketIds:[intent.marketId],candidateOffers:[f.wire(p.data.offer)],policyId:'test'});assert.equal(r.data.markets[0].knownOrders,1);assert.equal(r.data.decision,'reject');});
test('arbitrage rejects own orders and tampered commitments',async()=>{const f=setup(),p=await f.orderService.prepare(intent);const fill={offer:f.wire(p.data.offer),commitment:p.data.commitment,ratifierData:'0x' as const,units:'1'};await assert.rejects(f.service.arbitragePreview({account:maker.address,entry:[fill],exit:[fill],minProfit:'0'}),/INVALID_ARGUMENT/);const changed={...fill,offer:{...fill.offer,buy:false,maker:`0x${'77'.repeat(20)}`}};await assert.rejects(f.service.arbitragePreview({account:maker.address,entry:[changed],exit:[fill],minProfit:'0'}),/DOMAIN_MISMATCH/);});
