import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateTradePlan } from '../src/sdk/trade.ts';
import { adapterFor } from '../src/sdk/lineage.ts';
import { entryFromSignedOffer, fillCost } from '../src/sdk/orderbook.ts';
import { RATIFIED } from '../src/sdk/ratify.ts';
import type { Address, DeploymentProfile, Hex, Offer } from '../src/sdk/types.ts';
const a=(n:number)=>`0x${n.toString(16).padStart(40,'0')}` as Address;
const profile:DeploymentProfile={name:'test',abiProfile:'core-v2',chainId:46630,core:a(1),signatureRatifier:a(2),strategyRouter:a(8),rpcUrl:'http://127.0.0.1:1'};
const o:Offer={loanToken:a(3),collateralToken:a(4),maturity:1000n,strike:10n**36n,allowPartialRepay:true,gate:a(0),maker:a(5),buy:false,tick:4000n,maxUnits:1000n,maxAssets:0n,start:0n,expiry:900n,group:`0x${'00'.repeat(32)}`,ratifier:a(2)};
const adapter=adapterFor('core-v2');
function plan(offer=o,units=20n){const entry=entryFromSignedOffer(offer,adapter.offerCommitment(profile,offer),'0x');return {side:entry.side,takes:[{entry,units}],totalUnits:units,totalCost:fillCost(offer,units,entry.price)};}
function env(overrides:Record<string,unknown>={}) { const calls:any[]=[];return {calls,profile,account:a(6),block:{number:10n,timestamp:100n},read:async(r:any)=>{calls.push(r);return Object.hasOwn(overrides,r.functionName)?overrides[r.functionName]:({isRatifier:true,isRatified:RATIFIED,consumed:0n,creditOf:1000n,collateralEscrowOf:0n,liquidityOf:1000n} as any)[r.functionName];}}; }
test('read-only preflight uses exact units and actual taker at pinned block',async()=>{const e=env();await validateTradePlan(plan(),e);const r=e.calls.find(x=>x.functionName==='isRatified');assert.deepEqual(r.args.slice(0,3),[o.maker,e.account,20n]);assert.ok(e.calls.every(x=>x.blockNumber===10n));});
test('preflight rejects forged commitment and shared cap overfills',async()=>{const p=plan();p.takes[0].entry.commitment=`0x${'11'.repeat(32)}`;await assert.rejects(validateTradePlan(p,env()),/commitment/); const q=plan();await assert.rejects(validateTradePlan(q,env({consumed:990n})),/capacity/);});
test('sell cannot silently create debt; unknown ratifier fails closed',async()=>{await assert.rejects(validateTradePlan(plan({...o,buy:true}),env({creditOf:0n})),/debt/);await assert.rejects(validateTradePlan(plan({...o,ratifier:a(9)}),env()),/ratifier/i);});
import { evaluateAction } from '../src/sdk/actions/prepare.ts';
import { ActionContext } from '../src/sdk/actions/context.ts';
import { decodeFunctionData } from 'viem';
import type { ActionIntent } from '../src/sdk/actions/preview.ts';
function fixture(extra:Record<string,unknown>={}) {const p=plan();const calls:any[]=[];const marketId=adapter.computeMarketId(profile,o);const rpc:any={getChainId:async()=>46630,getBlock:async()=>({number:10n,hash:`0x${'11'.repeat(32)}`,timestamp:100n}),readContract:async(r:any)=>{calls.push(r);if(r.functionName==='computeId')return adapter.computeMarketId(profile,{loanToken:a(0),collateralToken:a(0),maturity:1n,strike:1n,allowPartialRepay:false,gate:a(0)}); if(Object.hasOwn(extra,r.functionName)){if(extra[r.functionName] instanceof Error)throw extra[r.functionName];return extra[r.functionName];}return ({decimals:18,isRatifier:true,isRatified:RATIFIED,creditOf:1000n,consumed:0n,collateralEscrowOf:0n,liquidityOf:1000n,balanceOf:1000n,allowance:1000n} as any)[r.functionName];},simulateContract:async(r:any)=>{calls.push({...r,simulation:true});return {};}};const context=new ActionContext({profile,rpc,markets:async()=>[{id:marketId,params:o}] as any});const intent:ActionIntent={action:'buy_dcn',marketId,account:a(6),receiver:a(6),policyId:'test',collateralKind:'other',evidence:{} as any,fills:[{offer:o,commitment:p.takes[0].entry.commitment,ratifierData:'0x',units:'20'}],maxCost:'20',deadline:'200'};return{context,intent,calls};}
test('unsigned direct buy encodes atomic fills and pins public simulation',async()=>{const f=fixture();const ctx=await f.context.pin(f.intent.account);const r=await evaluateAction(f.context,f.intent,ctx);const decoded=decodeFunctionData({abi:adapter.coreAbi,data:r.transaction.data});assert.equal(decoded.functionName,'multicall');assert.equal(r.simulation,'success');assert.ok(f.calls.filter(x=>x.simulation).every(x=>x.account===f.intent.account&&x.blockNumber===10n));});
test('trade rejects missed deadline and insufficient explicit price bound',async()=>{const f=fixture();const ctx=await f.context.pin(f.intent.account);await assert.rejects(evaluateAction(f.context,{...f.intent,deadline:'99'},ctx),/deadline/i);await assert.rejects(evaluateAction(f.context,{...f.intent,maxCost:'0'},ctx),/cost/i);});
test('gated lender routes through verified Core and includes lender fee, without defaulting failed reads',async()=>{const f=fixture({routers:[a(8)],LENDER_MUST_ROUTE:true,BIVIUM:profile.core,MAX_LEGS:16n,LENDER_FEE_BPS:1000n});const offer={...o,gate:a(7)};f.intent.marketId=adapter.computeMarketId(profile,offer);f.context.options.markets=async()=>[{id:f.intent.marketId,params:offer}] as any;f.intent.fills=[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}];const ctx=await f.context.pin(f.intent.account);const r=await evaluateAction(f.context,f.intent,ctx);assert.equal(r.transaction.to,a(8));const rat=f.calls.find(x=>x.functionName==='isRatified');assert.equal(rat.args[1],a(8));const broken=fixture({LENDER_FEE_BPS:new Error('RPC down'),BIVIUM:profile.core,MAX_LEGS:16n});broken.intent.router=a(8);await assert.rejects(evaluateAction(broken.context,broken.intent,await broken.context.pin(broken.intent.account)),/RPC down/);});
test('borrow grants only fill through bounded repreview window and does not simulate dependent execute',async()=>{const f=fixture({creditOf:0n,BIVIUM:profile.core,MAX_LEGS:16n,FEE_BPS:100n,grantOf:[0n,0n],position:{debt:10n,collateral:10n,collateralWithdrawable:0n}});const offer={...o,buy:true};f.intent={...f.intent,action:'borrow',maxCost:undefined,router:a(8),minProceeds:'0',maxTopUp:'20',fills:[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}]};const r=await evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account));assert.equal(r.simulation,'prerequisites_required');assert.equal(r.prerequisites.length,1);assert.deepEqual(decodeFunctionData({abi:(await import('../src/sdk/strategyRouter.ts')).grantAbi,data:r.prerequisites[0].data}).args,[a(8),4n,500n]);assert.ok(f.calls.filter(x=>x.simulation).every(x=>x.functionName==='grantAuthorization'));assert.equal((r.after as any).debt,30n);});
test('unsupported multi-leg catalog strategy never degrades to single borrow',async()=>{const f=fixture();f.intent={...f.intent,action:'strategy_program',strategyId:'collar'};await assert.rejects(evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account)),/supported|strategy/i);});
test('pre-maturity unsigned secondary sell refuses absent onchain no-origination guard',async()=>{const f=fixture();const offer={...o,buy:true};f.intent={...f.intent,action:'sell_dcn',maxCost:undefined,minProceeds:'0',fills:[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}]};await assert.rejects(evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account)),/secondary-only|origination guard/);});
test('shared validator rejects embedded foreign domain even if commitment recomputes',async()=>{const offer={...o,chainId:1n,bivium:a(9)};await assert.rejects(validateTradePlan(plan(offer),env()),/domain/i);});
test('mandatory lender routing with no approved routers fails closed',async()=>{const f=fixture({routers:[],LENDER_MUST_ROUTE:true});const offer={...o,gate:a(7)};f.intent.marketId=adapter.computeMarketId(profile,offer);f.context.options.markets=async()=>[{id:f.intent.marketId,params:offer}] as any;f.intent.fills=[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}];await assert.rejects(evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account)),/router/i);});
test('next block alone is not a key-state change',async()=>{const f=fixture();const ctx=await f.context.pin(f.intent.account);const first=await evaluateAction(f.context,f.intent,ctx);const next=await evaluateAction(f.context,f.intent,{...ctx,blockNumber:11n,timestamp:101n});assert.deepEqual(first.keyState,next.keyState);});
test('matured secondary sell encodes bids and preserves no-new-debt contract guard',async()=>{const f=fixture();const offer={...o,buy:true,maturity:50n};f.intent.marketId=adapter.computeMarketId(profile,offer);f.context.options.markets=async()=>[{id:f.intent.marketId,params:offer}] as any;f.intent={...f.intent,action:'sell_dcn',maxCost:undefined,minProceeds:'0',fills:[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}]};const r=await evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account));assert.equal((r.after as any).credit,980n);assert.equal(decodeFunctionData({abi:adapter.coreAbi,data:r.transaction.data}).functionName,'multicall');});
test('semantic lend strategy builds bound router program',async()=>{const f=fixture({BIVIUM:profile.core,MAX_LEGS:16n,LENDER_FEE_BPS:0n});f.intent={...f.intent,action:'strategy_program',strategyId:'lendAsset',router:a(8)};const r=await evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account));const decoded=decodeFunctionData({abi:(await import('../src/sdk/strategyRouter.ts')).routerAbi,data:r.transaction.data});assert.equal(decoded.functionName,'execute');assert.equal((decoded.args![0] as any)[0].kind,1);assert.equal(decoded.args![1],200n);});
test('semantic borrowing strategy verifies pool pair and requires explicit swap minimum',async()=>{const f=fixture({creditOf:0n,BIVIUM:profile.core,MAX_LEGS:16n,FEE_BPS:0n,grantOf:[4n,300n],position:{debt:0n,collateral:0n,collateralWithdrawable:0n}});const offer={...o,buy:true};f.intent={...f.intent,action:'strategy_program',maxCost:undefined,strategyId:'short',router:a(8),minProceeds:'0',maxTopUp:'20',fills:[{offer,commitment:adapter.offerCommitment(profile,offer),ratifierData:'0x',units:'20'}]};const ctx=await f.context.pin(f.intent.account);await assert.rejects(evaluateAction(f.context,f.intent,ctx),/minOut/);f.intent.minOut='1';f.intent.poolKey={currency0:a(3),currency1:a(9),fee:3000,tickSpacing:60,hooks:a(0)};await assert.rejects(evaluateAction(f.context,f.intent,ctx),/Pool key/);});
test('unused economic bounds are rejected by SDK evaluator itself',async()=>{const f=fixture();const ctx=await f.context.pin(f.intent.account);await assert.rejects(evaluateAction(f.context,{...f.intent,minProceeds:'1'},ctx),/minProceeds/);await assert.rejects(evaluateAction(f.context,{...f.intent,amount:'1'},ctx),/amount/);});
test('ungated arbitrary router cannot obtain approval by self-reporting expected Core',async()=>{
 const f=fixture({BIVIUM:profile.core,MAX_LEGS:16n,LENDER_FEE_BPS:0n,allowance:0n});
 f.intent.router=a(9);
 await assert.rejects(evaluateAction(f.context,f.intent,await f.context.pin(f.intent.account)),/trusted|configured/i);
 assert.equal(f.calls.some(c=>c.simulation),false);
});
