import {isAddress} from 'viem';
import {ActionContext, type ReadContext} from './context.ts';
import {accountState} from './reads.ts';
import {PublishJournal} from './orderJournal.ts';
import {ActionError,result} from './types.ts';
import {previewMarketMaking,type InventoryPolicy} from '../marketMaking.ts';
import {previewArbitrage,type CandidateLeg} from '../arbitrage.ts';
import {offerFromJson,marketParamsFromOffer} from '../offer.ts';
import {entryFromSignedOffer,fillCost,remainingFace,type BookEntry} from '../orderbook.ts';
import {fetchRelayerBook,wireOffer} from '../relayer.ts';
import {MAX_TICK} from '../tick.ts';
import type {SelectedRiskPolicy} from '../strategies/types.ts';
import type {Address,Hex,Offer,MarketParams} from '../types.ts';
export interface RawInventoryPolicy {maxCredit:string;maxNewDebt:string;minCash:string;maxCommittedLoan:string;maxLoss:string;allowOrigination:boolean;requireDailyLossAccounting?:boolean;}
export interface ConfiguredRiskPolicy extends SelectedRiskPolicy {inventory?:Record<string,RawInventoryPolicy>;}
export type WireAnalysisOffer=Record<string,unknown>;
export interface MMPreviewIntent {account:Address;marketIds:Hex[];candidateOffers:WireAnalysisOffer[];policyId:string;}
export interface AnalysisFill {offer:WireAnalysisOffer;commitment:Hex;ratifierData:Hex;units:string;}
export interface ArbitragePreviewIntent {account:Address;entry:AnalysisFill[];exit:AnalysisFill[];minProfit:string;gasBudget?:string;}
const MAX=(1n<<256n)-1n;
function strict(v:object,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v))throw new ActionError('INVALID_ARGUMENT','Expected object');for(const k of Object.keys(v))if(!keys.includes(k))throw new ActionError('INVALID_ARGUMENT',`Unused field: ${k}`);}
function uint(v:unknown):bigint {if(typeof v!=='string'||!/^\d+$/.test(v)||v.length>78||BigInt(v)>MAX)throw new ActionError('INVALID_ARGUMENT','Expected raw uint256 string');return BigInt(v);}
function hash(v:unknown):asserts v is Hex{if(typeof v!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(v))throw new ActionError('INVALID_ARGUMENT','Expected bytes32');}
const same=(a:string,b:string)=>a.toLowerCase()===b.toLowerCase();
/** Analysis accepts wire identities and rebuilds every economic field in the SDK. */
export class MarketAnalysisService {
 constructor(readonly context:ActionContext,readonly policies:Record<string,ConfiguredRiskPolicy>,readonly journal?:PublishJournal){}
 private offer(wire:WireAnalysisOffer):Offer {strict(wire,['chainId','bivium','loanToken','collateralToken','maturity','strike','allowPartialRepay','gate','maker','buy','tick','maxUnits','maxAssets','start','expiry','group','ratifier']);if(wire.chainId!==this.context.profile.chainId||typeof wire.bivium!=='string'||!same(wire.bivium,this.context.profile.core))throw new ActionError('DOMAIN_MISMATCH','Offer differs from configured chain/Core');for(const k of ['maturity','strike','tick','maxUnits','maxAssets','start','expiry'])uint(wire[k]);let o:Offer;try{o=offerFromJson(wire);}catch(e){throw new ActionError('INVALID_ARGUMENT',String(e));}if(o.strike===0n||(o.maxUnits===0n)===(o.maxAssets===0n)||o.tick>MAX_TICK||o.tick%4n!==0n||o.start>o.expiry)throw new ActionError('INVALID_ARGUMENT','Invalid cap, price grid or window');return o;}
 private inventory(policyId:string,id:Hex):InventoryPolicy {if(!Object.hasOwn(this.policies,policyId))throw new ActionError('POLICY_REJECTED','Unknown trusted policy');const raw=this.policies[policyId].inventory?.[id.toLowerCase()];if(!raw)throw new ActionError('POLICY_REJECTED',`No trusted inventory limits for ${id}`);strict(raw,['maxCredit','maxNewDebt','minCash','maxCommittedLoan','maxLoss','allowOrigination','requireDailyLossAccounting']);if(typeof raw.allowOrigination!=='boolean'||(raw.requireDailyLossAccounting!==undefined&&typeof raw.requireDailyLossAccounting!=='boolean'))throw new ActionError('POLICY_REJECTED','Invalid trusted inventory flags');return{maxCredit:uint(raw.maxCredit),maxNewDebt:uint(raw.maxNewDebt),minCash:uint(raw.minCash),maxCommittedLoan:uint(raw.maxCommittedLoan),maxLoss:uint(raw.maxLoss),allowOrigination:raw.allowOrigination,requireDailyLossAccounting:raw.requireDailyLossAccounting};}
 private entry(o:Offer,commitment?:Hex,signature:Hex='0x'):BookEntry{const actual=this.context.adapter.offerCommitment(this.context.profile,o);if(commitment&&!same(actual,commitment))throw new ActionError('DOMAIN_MISMATCH','Offer commitment mismatch');return entryFromSignedOffer(o,actual,signature);}
 private marketId(o:Offer){return this.context.adapter.computeMarketId(this.context.profile,marketParamsFromOffer(o));}
 private async book(params:MarketParams,ctx:ReadContext){if(this.context.options.book)return this.context.options.book(params,ctx.signal);if(!this.context.profile.relayerUrl)throw new Error('No relayer');const ratifiers=[...new Set([this.context.profile.signatureRatifier,this.context.profile.setterRatifier].filter((r):r is Address=>!!r))];const books=await Promise.all(ratifiers.map(ratifier=>fetchRelayerBook({...this.context.profile,relayerUrl:this.context.profile.relayerUrl!,ratifier},params,{signal:ctx.signal,nowSec:ctx.timestamp})));if(books.some(b=>!b.ok))throw new Error('Relayer unavailable');return{entries:books.flatMap(b=>b.ok?b.entries:[]),coverage:'unknown' as const};}
 async mmPreview(input:MMPreviewIntent,signal?:AbortSignal){strict(input,['account','marketIds','candidateOffers','policyId']);if(!isAddress(input.account)||!Array.isArray(input.marketIds)||input.marketIds.length<1||input.marketIds.length>20||!Array.isArray(input.candidateOffers)||input.candidateOffers.length>100)throw new ActionError('INVALID_ARGUMENT','Bounded account, markets and candidates required');input.marketIds.forEach(hash);const ids=input.marketIds.map(id=>id.toLowerCase() as Hex);if(new Set(ids).size!==ids.length)throw new ActionError('INVALID_ARGUMENT','Duplicate market');const limits=ids.map(id=>this.inventory(input.policyId,id));const candidates=input.candidateOffers.map(w=>this.entry(this.offer(w)));for(const e of candidates)if(!same(e.offer.maker,input.account)||!ids.includes(this.marketId(e.offer).toLowerCase() as Hex))throw new ActionError('DOMAIN_MISMATCH','Candidate maker/market outside requested inventory');const ctx=await this.context.pin(input.account,signal);ctx.snapshot.coverage='partial';ctx.snapshot.omitted.push('externally signed orders outside journal/relayer; full account order coverage unknown');
 const markets=await Promise.all(ids.map(async(id,index)=>{const state=await accountState(this.context,ctx,id,input.account);const omissions=[...state.omissions];let loaded:BookEntry[]=[];try{const book=await this.book(state.params,ctx);if(book.entries.length>100)omissions.push(`${id}.book truncated to 100 rows`);if(book.coverage!=='complete')omissions.push(`${id}.book coverage unknown`);loaded=book.entries.slice(0,100).map(e=>{const o=this.offer({...wireOffer(this.context.profile,e.offer),chainId:this.context.profile.chainId});if(!same(this.marketId(o),id))throw new ActionError('DOMAIN_MISMATCH','Relayer market mismatch');return this.entry(o,e.commitment,e.signature);}).filter(e=>same(e.offer.maker,input.account));}catch(e){if(e instanceof ActionError&&e.code==='DOMAIN_MISMATCH')throw e;omissions.push(`${id}.book unavailable`);}
 const journal=(this.journal?.records()??[]).filter(r=>r.chainId===ctx.chainId&&same(r.core,ctx.core)&&same(r.offer.maker,input.account)&&same(this.marketId(r.offer),id)).map(r=>this.entry(r.offer,r.commitment,r.signature));const unique=new Map<string,BookEntry>();for(const e of [...loaded,...journal,...candidates.filter(e=>same(this.marketId(e.offer),id))])unique.set(e.commitment.toLowerCase(),e);const entries=await Promise.all([...unique.values()].map(async e=>{try{const consumed=await this.context.core<bigint>(ctx,'consumed',[e.offer.maker,e.offer.group]);return{...e,consumed,size:remainingFace(e.offer,consumed,e.price)};}catch{omissions.push(`${id}.consumed.${e.offer.group} unavailable; full cap assumed`);return{...e,consumed:0n};}}));let analysis:ReturnType<typeof previewMarketMaking>|null=null;if(state.position!==null&&typeof state.position.debt==='bigint'&&state.credit!==null&&state.liquidity!==null&&state.collateralEscrow!==null&&state.loanBalance!==null)analysis=previewMarketMaking({account:input.account,marketId:id,params:state.params,now:ctx.timestamp,credit:state.credit,debt:state.position.debt,liquidity:state.liquidity,collateralEscrow:state.collateralEscrow,cash:state.loanBalance,existingOrders:entries,candidateOrders:[],coverage:'partial',policy:limits[index]});else omissions.push(`${id}.inventory analysis unavailable`);ctx.snapshot.omitted.push(...omissions);return{marketId:id,knownOrders:entries.length,state,analysis,omissions};}));await this.stable(ctx);return result({account:input.account,policyId:input.policyId,markets,accountSafe:false,fundsReserved:false,decision:markets.some(m=>m.analysis?.decision==='reject')?'reject' as const:'incomplete' as const,riskScreening:'Inventory limits do not replace collateral risk assessment during order preparation.'},ctx.snapshot);}
 private async stable(ctx:ReadContext){const block=await this.context.limited(()=>ctx.rpc.getBlock({blockNumber:ctx.blockNumber}),ctx.signal);if(block.hash!==ctx.blockHash)throw new ActionError('STATE_CHANGED','Snapshot reorganized during analysis');}
 async arbitragePreview(input:ArbitragePreviewIntent,signal?:AbortSignal){strict(input,['account','entry','exit','minProfit','gasBudget']);if(!isAddress(input.account))throw new ActionError('INVALID_ARGUMENT','Account required');const minProfit=uint(input.minProfit),gasBudget=input.gasBudget===undefined?null:uint(input.gasBudget);const ctx=await this.context.pin(input.account,signal);const leg=async(fills:AnalysisFill[],buy:boolean):Promise<CandidateLeg>=>{if(!Array.isArray(fills)||fills.length<1||fills.length>20)throw new ActionError('INVALID_ARGUMENT','Supply 1–20 explicit fills per leg');let marketId:Hex|undefined,token:Address|undefined,amount=0n,units=0n;const seen=new Set<string>();for(const fill of fills){strict(fill,['offer','commitment','ratifierData','units']);hash(fill.commitment);if(typeof fill.ratifierData!=='string'||fill.ratifierData.length>16386||!/^0x([0-9a-fA-F]{2})*$/.test(fill.ratifierData))throw new ActionError('INVALID_ARGUMENT','Ratifier data required');const offer=this.offer(fill.offer),entry=this.entry(offer,fill.commitment,fill.ratifierData),id=this.marketId(offer),n=uint(fill.units);if(n===0n||offer.buy!==buy||same(offer.maker,input.account)||seen.has(entry.commitment))throw new ActionError('INVALID_ARGUMENT','Wrong side, own order, duplicate or zero fill');seen.add(entry.commitment);if(marketId&&!same(id,marketId))throw new ActionError('DOMAIN_MISMATCH','Leg combines different settlement markets');marketId=id;token=offer.loanToken;await this.context.market(id,signal);units+=n;amount+=fillCost(offer,n,entry.price);}return{marketId:marketId!,token:token!,amount,units,feesIncluded:false,executionPriceKnown:true,depthKnown:false,ownOrder:false};};const [entry,exit]=await Promise.all([leg(input.entry,false),leg(input.exit,true)]);if(!same(entry.marketId,exit.marketId)||entry.units!==exit.units)throw new ActionError('INVALID_ARGUMENT','Entry/exit must share market and equal face units');const analysis=previewArbitrage({entry,exit,fees:null,gasBudget,minProfit});await this.stable(ctx);ctx.snapshot.coverage='partial';ctx.snapshot.omitted.push('fees, executable depth, authorization, gas cost and atomic simulation unverified');return result({...analysis,gasBudgetSource:gasBudget===null?'unknown':'caller_scenario_budget',executable:false,signaturesVerified:false},ctx.snapshot);}
}
