import { randomBytes, randomUUID } from 'node:crypto';
import { encodeFunctionData, getAddress, isAddress, hashTypedData, recoverAddress, verifyMessage, type Abi } from 'viem';
import { ActionContext, type ReadContext } from './context.ts';
import { ActionService, canonicalHash } from './preview.ts';
import { PublishJournal, type OrderRecord } from './orderJournal.ts';
import { ActionError, result, type UnsignedTx } from './types.ts';
import { buildOfferTree, encodeProofRatifierData, merkleRoot, RATIFIED, ratifyDigest, resolveRatifier, setterRatifierAbi } from '../ratify.ts';
import { cancelMessage, fetchRelayerBook, wireOffer } from '../relayer.ts';
import { remainingFace } from '../orderbook.ts';
import { marketParamsFromOffer } from '../offer.ts';
import { MAX_TICK, priceFromSimpleAprBps, priceToTick, tickToPrice } from '../tick.ts';
import { WAD, type Address, type Hex, type Offer } from '../types.ts';
import type { MarketRiskInput } from '../strategies/types.ts';
const MAX=(1n<<256n)-1n;
export interface OrderIntent {marketId:Hex; account:Address;side:'bid'|'ask';maxUnits?:string;maxAssets?:string;tick?:string;aprBps?:string;expiry:string;policyId:string;collateralKind:MarketRiskInput['collateralKind'];evidence:MarketRiskInput['evidence'];group:{mode:'independent'}|{mode:'shared';group:Hex;budgetUnit:'face'|'loan_assets'};ratifierKind?:'setter'|'signature';backing?:'secondary'|'origination';}
export interface CancelIntent{account:Address;offers:Offer[];mode:'selected_offers'|'group_permanent'|'root';root?:Hex;proofs?:Hex[][];}
function strict(v:object,keys:string[]){for(const k of Object.keys(v))if(!keys.includes(k))throw new ActionError('INVALID_ARGUMENT',`Unused field: ${k}`);}
function uint(v:unknown):bigint{if(typeof v!=='string'||!/^\d+$/.test(v)||BigInt(v)>MAX)throw new ActionError('INVALID_ARGUMENT','Expected raw uint256 decimal string');return BigInt(v);}
function bytes32(v:unknown):asserts v is Hex{if(typeof v!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(v))throw new ActionError('INVALID_ARGUMENT','Expected bytes32');}
function same(a:string,b:string){return a.toLowerCase()===b.toLowerCase();}
export class OrderService {
 readonly journal:PublishJournal; private active=new Set<string>();
 constructor(readonly context:ActionContext,readonly actions:ActionService,readonly options:{allowRelayerWrites?:boolean;journal?:PublishJournal;fetch?:typeof fetch}={}){this.journal=options.journal??new PublishJournal();}
 private async checkedRisk(input:OrderIntent,signal?:AbortSignal){const risk=await this.actions.risk(input.marketId,input.collateralKind,input.evidence,input.policyId,signal);if(risk.data.report.decision!=='accept')throw new ActionError('POLICY_REJECTED','Current trusted risk policy must accept this order');return risk.data;}
 private async backing(offer:Offer,marketId:Hex,ctx:ReadContext){
 const consumed=await this.context.core<bigint>(ctx,'consumed',[offer.maker,offer.group]);const face=remainingFace(offer,consumed,tickToPrice(offer.tick));if(face<=0n)throw new ActionError('STATE_CHANGED','Offer cap has been consumed');
 if(!offer.buy){const escrow=await this.context.core<bigint>(ctx,'collateralEscrowOf',[marketId,offer.maker]);if(escrow!==0n)throw new ActionError('SECONDARY_ONLY_UNAVAILABLE','Ask can originate from escrow; secondary preparation requires zero current escrow');}
 const balance=await this.context.core<bigint>(ctx,offer.buy?'liquidityOf':'creditOf',[marketId,offer.maker]);const required=offer.buy?(offer.maxAssets>0n?offer.maxAssets>consumed?offer.maxAssets-consumed:0n:face*tickToPrice(offer.tick)/WAD):face;
 if(required<=0n||required>balance)throw new ActionError('INSUFFICIENT_BALANCE','Full remaining offer exceeds current maker backing');
 }
 private async tx(ctx:ReadContext,to:Address,abi:readonly unknown[],functionName:string,args:readonly unknown[]):Promise<UnsignedTx>{if(!ctx.rpc.simulateContract)throw new ActionError('SIMULATION_UNAVAILABLE','Public simulation required');await this.context.limited(()=>ctx.rpc.simulateContract!({address:to,abi,functionName,args,account:ctx.account,blockNumber:ctx.blockNumber}),ctx.signal);return{chainId:ctx.chainId,from:ctx.account,to,data:encodeFunctionData({abi:abi as Abi,functionName,args}),value:'0'};}
 async prepare(input:OrderIntent,signal?:AbortSignal){
 strict(input,['marketId','account','side','maxUnits','maxAssets','tick','aprBps','expiry','policyId','collateralKind','evidence','group','ratifierKind','backing']);if(!isAddress(input.account)||!['bid','ask'].includes(input.side))throw new ActionError('INVALID_ARGUMENT','Invalid maker or side');bytes32(input.marketId);
 if(input.backing!==undefined&&!['secondary','origination'].includes(input.backing))throw new ActionError('INVALID_ARGUMENT','Invalid backing');if(input.backing==='origination')throw new ActionError('UNSUPPORTED_ACTION','Origination orders require escrow stress policy integration');
 if((input.maxUnits===undefined)===(input.maxAssets===undefined)||(input.tick===undefined)===(input.aprBps===undefined))throw new ActionError('INVALID_ARGUMENT','Exactly one cap and one tick/APR are required');
 const maxUnits=input.maxUnits===undefined?0n:uint(input.maxUnits),maxAssets=input.maxAssets===undefined?0n:uint(input.maxAssets);if(maxUnits+maxAssets===0n)throw new ActionError('INVALID_ARGUMENT','Positive cap required');
 if(!input.group||!['independent','shared'].includes(input.group.mode))throw new ActionError('INVALID_ARGUMENT','Explicit group mode required');strict(input.group,input.group.mode==='independent'?['mode']:['mode','group','budgetUnit']);
 if(input.ratifierKind!==undefined&&!['setter','signature'].includes(input.ratifierKind))throw new ActionError('INVALID_ARGUMENT','Invalid ratifier kind');
 const intent=structuredClone(input);intent.account=getAddress(input.account);const assessment=await this.checkedRisk(intent,signal);this.context.requireExecutable();const ctx=await this.context.pin(intent.account,signal),market=await this.context.market(intent.marketId,signal);
 const expiry=uint(intent.expiry);if(expiry<=ctx.timestamp||expiry>market.params.maturity-3600n)throw new ActionError('INVALID_ARGUMENT','Expiry must be future and before market trading cutoff');const tick=intent.tick===undefined?priceToTick(priceFromSimpleAprBps(uint(intent.aprBps),market.params.maturity-ctx.timestamp),intent.side==='ask'):uint(intent.tick);if(tick>MAX_TICK||tick%4n!==0n)throw new ActionError('INVALID_ARGUMENT','Tick must lie on tick grid');
 const ratifier=resolveRatifier(this.context.profile,intent.ratifierKind);let group:Hex=`0x${randomBytes(32).toString('hex')}`;
 if(intent.group.mode==='shared'){bytes32(intent.group.group);group=intent.group.group;const currency=maxAssets>0n?'loan_assets':'face';if(intent.group.budgetUnit!==currency)throw new ActionError('INVALID_ARGUMENT','Group budget currency differs from cap');for(const r of this.journal.records())if(r.chainId===ctx.chainId&&same(r.core,ctx.core)&&same(r.offer.maker,intent.account)&&same(r.offer.group,group)&&(r.offer.maxAssets>0n)!==(maxAssets>0n))throw new ActionError('INVALID_ARGUMENT','Known group mixes cap currencies');}
 const offer:Offer={...market.params,maker:intent.account,buy:intent.side==='bid',tick,maxUnits,maxAssets,start:ctx.timestamp,expiry,group,ratifier:ratifier.address};await this.backing(offer,intent.marketId,ctx);
 const commitment=this.context.adapter.offerCommitment(this.context.profile,offer);const digest=ratifyDigest(ctx.chainId,ratifier.address,commitment);
 const typedData={domain:{chainId:ctx.chainId,verifyingContract:ratifier.address},types:{Ratify:[{name:'commitment',type:'bytes32'}]},primaryType:'Ratify' as const,message:{commitment}};if(hashTypedData(typedData)!==digest)throw new ActionError('DOMAIN_MISMATCH','EIP712 digest mismatch');
 const prerequisites:UnsignedTx[]=[];let transaction:UnsignedTx|undefined,root:Hex|undefined,proof:Hex[]|undefined;
 if(ratifier.kind==='signature'){if(!ctx.rpc.getBytecode)throw new ActionError('UPSTREAM_UNAVAILABLE','Maker code check unavailable');const code=await ctx.rpc.getBytecode({address:intent.account,blockNumber:ctx.blockNumber});if(code&&code!=='0x')throw new ActionError('CONTRACT_MAKER','Signature ratifier supports EOA makers only');}
 else{const tree=buildOfferTree([commitment]);root=tree.root;proof=tree.proofs[0];const registered=await this.context.core<boolean>(ctx,'isRatifier',[intent.account,ratifier.address]);if(!registered)prerequisites.push(await this.tx(ctx,ctx.core,this.context.adapter.coreAbi,'setRatifier',[ratifier.address,true]));transaction=await this.tx(ctx,ratifier.address,setterRatifierAbi,'setRootRatified',[intent.account,root,true]);}
 const finalBlock=await this.context.limited(()=>ctx.rpc.getBlock({blockNumber:ctx.blockNumber}),signal);if(finalBlock.hash!==ctx.blockHash)throw new ActionError('STATE_CHANGED','Snapshot reorganized during order preparation');if(BigInt(Math.floor(this.context.now()/1000))>=expiry)throw new ActionError('EXPIRED','Offer expired during preparation');
 const prepareId=randomUUID();this.journal.put({prepareId,state:'prepared',chainId:ctx.chainId,core:ctx.core,intent,offer,commitment,policyHash:assessment.policyHash,evidenceHash:assessment.evidenceHash,ratifierKind:ratifier.kind,root,proof});
 return result({prepareId,offer,commitment,ratifierKind:ratifier.kind,typedData:ratifier.kind==='signature'?typedData:undefined,ratifyDigest:digest,root,proof,ratifierData:proof?encodeProofRatifierData(proof):undefined,transaction,prerequisites,rootCovers:root?[commitment]:[],dependency:'Register the ratifier before relying on an approved root. External wallet signs/sends unsigned transactions.',backingLimitation:'Backing is current only; later credit withdrawal or escrow deposit can change ask behavior, including permitting origination.'},ctx.snapshot);
 }
 async cancelPrepare(input:CancelIntent,signal?:AbortSignal){strict(input,['account','offers','mode','root','proofs']);if(!isAddress(input.account)||!Array.isArray(input.offers)||input.offers.length<1||input.offers.length>100||!['selected_offers','group_permanent','root'].includes(input.mode))throw new ActionError('INVALID_ARGUMENT','Invalid cancellation');if(input.mode!=='root'&&(input.root!==undefined||input.proofs!==undefined))throw new ActionError('INVALID_ARGUMENT','Root fields unused');this.context.requireExecutable();const ctx=await this.context.pin(input.account,signal);for(const o of input.offers){this.validateOffer(o);if(!same(o.maker,input.account))throw new ActionError('MAKER_MISMATCH','Every offer must belong to account');}
 const transactions:UnsignedTx[]=[],groups:Array<{group:Hex;amount:string}>=[];let scope='Selected known offers only; unknown higher caps in these groups remain usable.';let associated:Hex[]=[];
 if(input.mode==='root'){bytes32(input.root);if(!input.proofs||input.proofs.length!==input.offers.length)throw new ActionError('INVALID_ARGUMENT','Exact root proofs required');const ratifier=this.context.profile.setterRatifier;if(!ratifier)throw new ActionError('UNSUPPORTED_ACTION','No setter ratifier');for(let i=0;i<input.offers.length;i++){const o=input.offers[i];const c=this.context.adapter.offerCommitment(this.context.profile,o);input.proofs[i].forEach(bytes32);if(!same(o.ratifier,ratifier)||!same(merkleRoot(c,input.proofs[i]),input.root))throw new ActionError('INVALID_ARGUMENT','Offer proof does not belong to setter root');associated.push(c);}associated=[...new Set([...associated,...this.journal.records().filter(r=>r.chainId===ctx.chainId&&same(r.core,ctx.core)&&same(r.offer.maker,input.account)&&r.root&&same(r.root,input.root!)).map(r=>r.commitment)])];transactions.push(await this.tx(ctx,ratifier,setterRatifierAbi,'setRootRatified',[input.account,input.root,false]));scope='Revokes the actual root, affecting every associated offer including unknown leaves; associated lists known commitments only.';
 }else{const caps=new Map<Hex,bigint>();for(const o of input.offers){const cap=o.maxAssets||o.maxUnits,key=o.group.toLowerCase() as Hex;caps.set(key,cap>(caps.get(key)??0n)?cap:caps.get(key)!);}for(const[group,cap]of caps){const old=await this.context.core<bigint>(ctx,'consumed',[input.account,group]);const amount=input.mode==='group_permanent'?MAX:old>cap?old:cap;groups.push({group,amount:String(amount)});transactions.push(await this.tx(ctx,ctx.core,this.context.adapter.coreAbi,'setConsumed',[group,amount,input.account]));}if(input.mode==='group_permanent')scope='Permanently consumes the named groups to uint256 max, including unknown and future offers.';}
 return result({transactions,groups,scope,associated,onchainCancelled:'unknown'},ctx.snapshot);
 }
 private validateOffer(o:Offer){strict(o,['loanToken','collateralToken','maturity','strike','allowPartialRepay','gate','maker','buy','tick','maxUnits','maxAssets','start','expiry','group','ratifier']);for(const k of ['loanToken','collateralToken','gate','maker','ratifier'] as const)if(!isAddress(o[k]))throw new ActionError('INVALID_ARGUMENT','Invalid offer address');for(const k of ['maturity','strike','tick','maxUnits','maxAssets','start','expiry'] as const)if(typeof o[k]!=='bigint'||o[k]<0n||o[k]>MAX)throw new ActionError('INVALID_ARGUMENT','Offer amounts must be uint256 bigint');bytes32(o.group);if(typeof o.buy!=='boolean'||typeof o.allowPartialRepay!=='boolean'||(o.maxUnits===0n)===(o.maxAssets===0n)||o.tick>MAX_TICK||o.tick%4n!==0n||o.start>o.expiry||o.expiry>o.maturity-3600n)throw new ActionError('INVALID_ARGUMENT','Malformed offer');}
 private writable(){if(!this.options.allowRelayerWrites)throw new ActionError('RELAYER_WRITES_DISABLED','Relayer writes require host opt in');if(!this.journal.persistent)throw new ActionError('PERSISTENT_JOURNAL_REQUIRED','Writes require persistent host journal');if(!this.context.profile.relayerUrl)throw new ActionError('UPSTREAM_UNAVAILABLE','No configured relayer');this.context.requireExecutable();}
 async publish(input:{prepareId:string;signature?:Hex},signal?:AbortSignal){strict(input,['prepareId','signature']);this.writable();if(this.active.has(input.prepareId))throw new ActionError('PUBLISH_IN_PROGRESS','Concurrent publication refused');this.active.add(input.prepareId);try{return await this.publishOne(input,signal);}finally{this.active.delete(input.prepareId);}}
 private async publishOne(input:{prepareId:string;signature?:Hex},signal?:AbortSignal){const row=this.journal.get(input.prepareId);if(row.chainId!==this.context.profile.chainId||!same(row.core,this.context.profile.core)||this.context.adapter.offerCommitment(this.context.profile,row.offer)!==row.commitment)throw new ActionError('DOMAIN_MISMATCH','Stored order differs from deployment');if(row.signature&&input.signature&&row.signature!==input.signature)throw new ActionError('INVALID_ARGUMENT','Cannot replace previously exported signature');const risk=await this.checkedRisk(row.intent,signal);if(risk.policyHash!==row.policyHash||risk.evidenceHash!==row.evidenceHash)throw new ActionError('STATE_CHANGED','Bound policy or evidence changed');const ctx=await this.context.pin(row.offer.maker,signal);if(ctx.timestamp>=row.offer.expiry)throw new ActionError('EXPIRED','Prepared offer expired');await this.backing(row.offer,row.intent.marketId,ctx);
 let signature=row.signature??input.signature;if(row.ratifierKind==='signature'){if(!signature)throw new ActionError('INVALID_ARGUMENT','External maker signature required');const code=await ctx.rpc.getBytecode?.({address:row.offer.maker,blockNumber:ctx.blockNumber});if(!ctx.rpc.getBytecode||(code&&code!=='0x'))throw new ActionError('CONTRACT_MAKER','EOA code verification required');if(!same(await recoverAddress({hash:ratifyDigest(ctx.chainId,row.offer.ratifier,row.commitment),signature}),row.offer.maker))throw new ActionError('INVALID_SIGNATURE','Signature is not maker authorization');}else{if(input.signature!==undefined)throw new ActionError('INVALID_ARGUMENT','Setter proof comes from stored preparation');signature=encodeProofRatifierData(row.proof!);}
 if(!await this.context.core<boolean>(ctx,'isRatifier',[row.offer.maker,row.offer.ratifier]))throw new ActionError('RATIFIER_NOT_REGISTERED','Maker ratifier is not registered');const ratified=await this.context.read<Hex>(ctx,row.offer.ratifier,this.context.adapter.ratifierAbi,'isRatified',this.context.adapter.ratifierArgs(row.offer.maker,1n,row.commitment,signature));if(!same(ratified,RATIFIED))throw new ActionError('NOT_RATIFIED','Exact offer is not currently ratified');
 const payload=JSON.stringify({offer:wireOffer(this.context.profile,row.offer),signature,commitment:row.commitment});if(row.signedPayload&&row.signedPayload!==payload)throw new ActionError('STATE_CHANGED','Retry signed payload differs');const prior=row.state;row.signature=signature;row.signedPayload=payload;if(prior==='published')return result({prepareId:row.prepareId,state:row.state,commitment:row.commitment},ctx.snapshot);
 if(prior==='submission_unknown'||prior==='publishing'){const book=await fetchRelayerBook({...this.context.profile,relayerUrl:this.context.profile.relayerUrl!,ratifier:row.offer.ratifier},marketParamsFromOffer(row.offer),{signal,nowSec:ctx.timestamp});if(!book.ok)throw new ActionError('SUBMISSION_UNKNOWN','Cannot inspect relayer before retry',true);if(book.entries.some(e=>same(e.commitment,row.commitment)&&same(e.signature,signature!))){row.state='published';this.journal.put(row);return result({prepareId:row.prepareId,state:row.state,commitment:row.commitment},ctx.snapshot);}}
 const finalBlock=await this.context.limited(()=>ctx.rpc.getBlock({blockNumber:ctx.blockNumber}),signal);if(finalBlock.hash!==ctx.blockHash)throw new ActionError('STATE_CHANGED','Snapshot reorganized before publication');if(BigInt(Math.floor(this.context.now()/1000))>=row.offer.expiry)throw new ActionError('EXPIRED','Offer expired before submission');
 row.state='signed';this.journal.put(row);row.state='publishing';this.journal.put(row);
 try{const response=await(this.options.fetch??fetch)(`${this.context.profile.relayerUrl!.replace(/\/$/,'')}/offers`,{method:'POST',headers:{'content-type':'application/json'},body:payload,signal:AbortSignal.any([AbortSignal.timeout(8000),...(signal?[signal]:[])])});const body=await response.json() as {commitment?:unknown;error?:unknown};if(response.ok&&body&&typeof body==='object'&&typeof body.commitment==='string'&&same(body.commitment,row.commitment))row.state='published';else if(!response.ok&&response.status>=400&&response.status<500&&typeof body?.error==='string'){row.state='rejected';row.reason=body.error;}else row.state='submission_unknown';}catch(e){row.state='submission_unknown';row.reason=e instanceof Error?e.message:String(e);}this.journal.put(row);return result({prepareId:row.prepareId,state:row.state,commitment:row.commitment},ctx.snapshot);
 }
 async delist(input:{offer:Offer;commitment:Hex;cancelSignature:Hex},signal?:AbortSignal){strict(input,['offer','commitment','cancelSignature']);this.writable();this.validateOffer(input.offer);bytes32(input.commitment);const commitment=this.context.adapter.offerCommitment(this.context.profile,input.offer);if(!same(commitment,input.commitment))throw new ActionError('DOMAIN_MISMATCH','Offer identity mismatch');if(!await verifyMessage({address:input.offer.maker,message:cancelMessage(commitment),signature:input.cancelSignature}))throw new ActionError('INVALID_SIGNATURE','External maker cancel signature required');const response=await(this.options.fetch??fetch)(`${this.context.profile.relayerUrl!.replace(/\/$/,'')}/offers`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({offer:wireOffer(this.context.profile,input.offer),commitment,signature:input.cancelSignature}),signal:AbortSignal.any([AbortSignal.timeout(8000),...(signal?[signal]:[])])});if(!response.ok)throw new ActionError('UPSTREAM_UNAVAILABLE','Relayer did not confirm delisting',true);return result({commitment,relayerRemoved:true,onchainCancelled:'unknown',authority:'Relayer removal is advisory; signed offer remains executable on chain.'},null);}
}
